### ISSUE TITLE
Bot not adding reactions

### ISSUE THREAD

**Issue by tsc0w** [eibex/reaction-light#41]
My bot isn't adding reactions.

So i tried to make a reaction message today and it all worked except when the bot tried to add the reactions, it had enough permissions to do so, its just the fact it outputted this error:

```
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\DiscordBotExport\FlickzReactions\reaction-light-master\bot.py", line 363, in on_message
    "I could not commit the changes to the database. Check"
AttributeError: 'int' object has no attribute 'mention'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\DiscordBotExport\FlickzReactions\reaction-light-master\bot.py", line 363, in on_message
    "I could not commit the changes to the database. Check"
AttributeError: 'int' object has no attribute 'mention'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\DiscordBotExport\FlickzReactions\reaction-light-master\bot.py", line 363, in on_message
    "I could not commit the changes to the database. Check"
AttributeError: 'int' object has no attribute 'mention'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\DiscordBotExport\FlickzReactions\reaction-light-master\bot.py", line 363, in on_message
    "I could not commit the changes to the database. Check"
AttributeError: 'int' object has no attribute 'mention'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\DiscordBotExport\FlickzReactions\reaction-light-master\bot.py", line 363, in on_message
    "I could not commit the changes to the database. Check"
AttributeError: 'int' object has no attribute 'mention'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\DiscordBotExport\FlickzReactions\reaction-light-master\bot.py", line 363, in on_message
    "I could not commit the changes to the database. Check"
AttributeError: 'int' object has no attribute 'mention'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\DiscordBotExport\FlickzReactions\reaction-light-master\bot.py", line 363, in on_message
    "I could not commit the changes to the database. Check"
AttributeError: 'int' object has no attribute 'mention'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\DiscordBotExport\FlickzReactions\reaction-light-master\bot.py", line 363, in on_message
    "I could not commit the changes to the database. Check"
AttributeError: 'int' object has no attribute 'mention'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\DiscordBotExport\FlickzReactions\reaction-light-master\bot.py", line 363, in on_message
    "I could not commit the changes to the database. Check"
AttributeError: 'int' object has no attribute 'mention'
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "C:\DiscordBotExport\FlickzReactions\reaction-light-master\bot.py", line 363, in on_message
    "I could not commit the changes to the database. Check"
AttributeError: 'int' object has no attribute 'mention'
```
It would mean a lot of you could help, thank you!

**Comment by eibex** [comment]
Should be fixed now. It was an oversight from the last update. Sorry.

**Comment by tsc0w** [comment]
All good, how will i be able to fix this, as its still not adding reactions, will i need to download it all again?

**Comment by eibex** [comment]
Yes, you need to `git pull` again, or download it as a zip and extract the contents on top of the existing files.
